logging:
  level: error
  level.org.apache.pdfbox.*: fatal

services.remote:
  semantic:
    url: "http://10.80.22.5:8081/classificator/api/rest/1.0/classify"

spring:
  data:
    mongodb:
      host: "10.80.22.5"
      port: 27017
      database: dms
      uri: "mongodb://10.80.22.5"
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  datasource:
    url: jdbc:mariadb://10.80.22.5:3306/dmsusers
    username: dmsuser
    password: dmspassword
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 28800
  jpa:
    hibernate:
      ddl-auto: validate
